apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: star-trek-quiz
  namespace: argocd

spec:
  project: star-trek-quiz-project

  source:
    repoURL: https://github.com/dsohar/star-trek-quiz.git
    targetRevision: main
    path: helmchart

  destination:
    server: https://kubernetes.default.svc
    namespace: default